[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

ignored_error_codes = [ "unused-param", "shadowing", "license", "func-mutability" ]

# To enable compilation of Vyper, Yul and Huff contracts 
ffi = true

# Whether to append the metadata hash to the bytecode
cbor_metadata = false
bytecode_hash = "none"

verbosity = 3
gas_limit = 30000000

evm_version = "shanghai"

[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
