[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

ffi = true
ignored_error_codes = [ "unused-param" ]

# Whether to append the metadata hash to the bytecode
cbor_metadata = false
bytecode_hash = "none"

verbosity = 3
gas_limit = 30000000

[fuzz]
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
