[[levels]]
id = "1"
file = "S01E01-Average"
name = "Average"
test = "AverageTest"
description = "Lorem ipsum dolor dolor sit amet"

[[levels]]
id = "2"
file = "S01E02-Test"
name = "Test"
test = "TestTest"
description = "Lorem ipsum dolor dolor sit amet"
