[[levels]]
id = "1"
file = "S01E01-Average"
contract = "Average"
type = "unsigned math"
description = """ /**
  * Write a function to find the average of two unsigned integers.
  *
  * average(1,1) == 1
  * average(1,2) == 1
  * average(2,1) == 1
  * average(0,4) == 2
  */
"""

[[levels]]
id = "2"
file = "S01E02-FibHash"
contract = "FibHash"
type = "hashing"
description = """ /**
  * Write a fibonacci hash function with inputs x and k,
  * where x is the 64-bit number to be hashed 
  * and 2^k is the resulting size of the hash table
  * 
  * fibhash(0, 3) == 0
  * fibhash(5, 6) == 5
  * fibhash(12345, 10) == 644
  * fibhash(1000_000, 10) == 1012
  */
"""


[[levels]]
id = "3"
file = "S01E03-Fibonacci"
contract = "Fibonacci"
type = "loops"
description = """ /**
  * Calculate the n-th Fibonacci number.
  *
  * fibonacci(0) == 0
  * fibonacci(1) == 1
  * fibonacci(5) == 5
  * fibonacci(20) == 6765
  *
  * Note: Use the modulo operator to prevent the result from overflowing.
  */
"""
