[[levels]]
id = "1"
file = "S01E01-Average"
contract = "Average"
type = "unsigned math"
description = """ /**
  * Write a function to find the average of two unsigned integers.
  * More info: https://devblogs.microsoft.com/oldnewthing/20220207-00/?p=106223
  *
  * average(1,1) == 1
  * average(1,2) == 1
  * average(2,1) == 1
  * average(0,4) == 2
  */
"""

[[levels]]
id = "2"
file = "S01E02-FibHash"
contract = "FibHash"
type = "hashing"
description = """ /**
  * Write a fibonacci hash function with inputs x and k, where x is the 256-bit
  * number to be hashed and 2^k is the resulting size of the hash table
  * More info: https://bit.ly/fibonacci-hashing
  * See also: https://bit.ly/multiplication-hashing
  *
  * fibhash(0, 3) == 0
  * fibhash(5, 6) == 5
  * fibhash(12345, 10) == 644
  * fibhash(1000_000, 10) == 1012
  *
  * See function _fibhash in the base test contract for an example implementation
  */
"""


[[levels]]
id = "3"
file = "S01E03-Fibonacci"
contract = "Fibonacci"
type = "loops/math"
description = """ /**
  * Calculate the n-th Fibonacci number.
  * Note: Use the modulo operator to prevent the result from overflowing.  
  *
  * fibonacci(0) == 0
  * fibonacci(1) == 1
  * fibonacci(5) == 5
  * fibonacci(20) == 6765
  */
"""

[[levels]]
id = "4"
file = "S01E04-Prime"
contract = "Prime"
type = "loops/math"
description = """ /**
  * Check if a given input number is prime
  *
  * isPrime(0) == false
  * isPrime(2) == true
  * isPrime(4) == false
  * isPrime(7) == true
  */
"""
